pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                    withAnt() {
                        sh "ant clean dist-all"
                }
            }
        }
    }

    post {
        success {
               archiveArtifacts artifacts: 'dist/*/chipkit-core-*.zip', fingerprint: true
       }
    }
}
